//LANGUAGES TYPES
export const CHANGE_LANG = "CHANGE_LANG";

//ERRORS TYPES
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

//USER TYPES
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USERS = "GET_USERS";
export const GET_USER = "GET_USER";
export const EDIT_USER = "EDIT_USER";
export const DELETE_USER = "DELETE_USER";

//PRODUCTS TYPES
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_FOR_USERS = "GET_PRODUCTS_FOR_USERS";
export const GET_PRODUCT = "GET_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

//CATEGORIES TYPES
export const ADD_CATEGORY = "ADD_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORY = "GET_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";

//BRANDS TYPES
export const ADD_BRAND = "ADD_BRAND";
export const GET_BRANDS = "GET_BRANDS";
export const GET_BRAND = "GET_BRAND";
export const DELETE_BRAND = "DELETE_BRAND";
export const EDIT_BRAND = "EDIT_BRAND";

//CART TYPES
export const ADD_CART = "ADD_CART";
export const GET_CART = "GET_CART";
export const PRODUCT_INC_DEC = "PRODUCT_INC_DEC";
export const PRODUCT_DELETE = "PRODUCT_DELETE";
export const CLEAR_CART = "CLEAR_CART";

//ORDERS TYPES
export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDER = "GET_ORDER";
export const DELETE_ORDER = "DELETE_ORDER";
export const EDIT_ORDER = "EDIT_ORDER";

//POSTS TYPES
export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const ADD_POSTS = "ADD_POSTS";
export const EDIT_POST = "EDIT_POST";
export const DELETE_POST = "DELETE_POST";

//NOTIFIES TYPES
export const ADD_NOTIFY = "ADD_NOTIFY";
export const GET_NOTIFIES = "GET_NOTIFIES";
export const DELETE_NOTIFIY = "DELETE_NOTIFIY";
export const DELETE_NOTIFIIES = "DELETE_NOTIFIIES";

//CHECKOUT TYPES
export const STRIPE = "STRIPE";
export const CLIENT_SECRET = "CLIENT_SECRET";
